[package]
name = "nova_debug"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false
description = "Debugging utilities for the Nova Protocol game"

[dependencies]
avian3d = { version = "0.7", features = ["diagnostic_ui"] }
bevy = { version = "0.19.0", features = ["track_location"] }
bevy-inspector-egui = { version = "0.37" }
dirs = "6"
itertools = { version = "0.15.0" }
bevy_mod_debugdump = { version = "0.16" }
nova_autopilot = { path = "../nova_autopilot" }
nova_events = { path = "../nova_events" }
nova_gameplay = { path = "../nova_gameplay" }
nova_ship = { path = "../nova_ship" }
nova_hud = { path = "../nova_hud" }
nova_scenario = { path = "../nova_scenario" }

[lints]
workspace = true
