[book]
title = "Nova Protocol Encyclopedia"
authors = ["Alex Jercan"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["theme/crt.css"]
no-section-label = true
