#!/usr/bin/env python3
"""Export requested standalone panel scenes. No story parsing or page assembly."""

import argparse
import importlib.util
import json
from pathlib import Path
import re
import sys
from xml.etree import ElementTree as ET

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
from nova_illustration import colors
from nova_illustration.scenes import Scene, render_scene


def put(file, content):
    """Preserve unchanged generated bytes and mtimes for watch builds."""
    if not file.exists() or file.read_text()!=content:
        file.write_text(content)


def main():
    """Load registered art modules and call only requested scene functions."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',type=Path,action='append',required=True)
    parser.add_argument('--scenes',required=True,help='JSON array of selected scene ids')
    parser.add_argument('--output',type=Path,required=True)
    args = parser.parse_args()
    output = args.output.resolve()
    cache = ROOT/'web/.cache/story'
    if output.is_relative_to(ROOT) and not output.is_relative_to(cache):
        raise ValueError('Comic output must be an isolated generated cache')
    if any(source.resolve().is_relative_to(output) for source in args.source):
        raise ValueError('Comic output overlaps source')
    requested = json.loads(args.scenes)
    if not isinstance(requested,list) or not requested or any(not isinstance(k,str) or not re.fullmatch(r'[a-z0-9][a-z0-9-]*',k) for k in requested):
        raise ValueError('Invalid requested scene ids')
    scenes = {}
    for source in args.source:
        source = source.resolve()
        sys.path.insert(0,str(source.parent))
        spec = importlib.util.spec_from_file_location(source.stem,source)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        if not isinstance(getattr(module,'SCENES',None),dict):
            raise ValueError(f'{source.name} registers no SCENES dict')
        for key,draw in module.SCENES.items():
            if not re.fullmatch(r'[a-z0-9][a-z0-9-]*',key) or key in scenes or not callable(draw):
                raise ValueError(f'Invalid or duplicate scene registration: {key}')
            scenes[key] = draw
    # The caller picks scene ids out of the episode script, so a typo or a
    # renamed scene arrives here and nowhere earlier. Name every id that is
    # missing, and what IS on offer, instead of a bare KeyError on the first.
    missing = [key for key in dict.fromkeys(requested) if key not in scenes]
    if missing:
        raise ValueError(f'Unregistered scene ids: {", ".join(missing)}. Registered: {", ".join(sorted(scenes))}')
    output.mkdir(parents=True,exist_ok=True)
    metadata = {}
    for key in dict.fromkeys(requested):
        scene = scenes[key]()
        if not isinstance(scene,Scene):
            raise TypeError(f'{key} did not return a Scene')
        source = render_scene(scene)
        slots = [n.get('data-story-slot') for n in ET.fromstring(source).iter() if n.get('data-story-slot')]
        if len(slots)!=len(set(slots)):
            raise ValueError(f'Duplicate text slot in {key}')
        file = f'{key}.svg'
        put(output/file,source)
        metadata[key] = dict(file=file,size=[scene.width,scene.height],slots=slots)
    palette = {name.lower():getattr(colors,name) for name in ('INK','PAPER','MINT','JADE')}
    palette.update(balloon=colors.CREAM,speaker=colors.FOLIO['title'])
    for name in ('WORK','FOLIO','INTERIOR'):
        palette.update({f'{name.lower()}-{k.replace("_","-")}':v for k,v in getattr(colors,name).items()})
    put(output/'scenes.json',json.dumps(metadata,indent=2)+'\n')
    put(output/'palette.json',json.dumps(palette,indent=2)+'\n')


if __name__=='__main__':
    main()
